version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    reviewers:
      - dedoussis
    labels:
      - dependencies
    commit-message:
      prefix: "deps: "
  - package-ecosystem: pip
    directory: /example
    schedule:
      interval: daily
    reviewers:
      - dedoussis
    labels:
      - dependencies
    commit-message:
      prefix: "deps: "
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - dedoussis
    labels:
      - dependencies
    commit-message:
      prefix: "deps: "
  - package-ecosystem: docker
    directory: /example
    schedule:
      interval: weekly
    reviewers:
      - dedoussis
    labels:
      - dependencies
    commit-message:
      prefix: "deps: "
  - package-ecosystem: npm
    directory: /example/client
    schedule:
      interval: weekly
    reviewers:
      - dedoussis
    labels:
      - dependencies
    commit-message:
      prefix: "deps: "
