version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    default_reviewers:
      - dedoussis
    default_labels:
      - dependencies
    commit_message:
      prefix: "deps:"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    default_reviewers:
      - dedoussis
    default_labels:
      - dependencies
    commit_message:
      prefix: "deps:"
  - package-ecosystem: docker
    directory: /example
    schedule:
      interval: weekly
    default_reviewers:
      - dedoussis
    default_labels:
      - dependencies
    commit_message:
      prefix: "deps:"
  - package-ecosystem: npm
    directory: /example/client
    schedule:
      interval: weekly
    default_reviewers:
      - dedoussis
    default_labels:
      - dependencies
    commit_message:
      prefix: "deps:"
