name: test
on: [push]
jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: make requirements-install
      - name: Install test dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: make requirements-test-install
      - name: Linting
        run: make lint
      - name: Type Checking
        run: make typecheck
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: make requirements-install
      - name: Install test dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: make requirements-test-install
      - name: Test
        run: make test
